language: php
php:
- 7.1
before_script:
- cp .env.testing .env
- touch database/database.sqlite
- composer self-update
- composer install --no-interaction
script:
- php artisan key:generate
- php artisan storage:link
- mkdir public/storage/recommend
- vendor/bin/phpunit
notifications:
  email: false
  slack:
    on_success: change
    secure: IkbQUSv4OT4pZr5BvVRakClK+Azt3fUSRzL20fNKKHaKX0G29P0djatZMULEjlee7GZuBX1RKu3KGZCxFFMkTVdfzuPqFZiXJ7s7lteDs8gy/i+9SI1FGs8AS7exJkCm3MBy+qMBeHmU43wlEyDA6+DgPXNu2bzlYbucq3ZB4fwvEP3EjmEjdUPVgVLbRlHFt1Q6PXDspF8Ebl2SFC/Vn1JtGJOwl1k45oOSfcrFlY45QNxhndWC08sarTzhn0FjLtMZc2yF2u4KSFjO8gveP+AdkyYROIqXuOv4f9NwXujC9MEjD5VqIm0uYQ3tu6wO4D1331lmzT+w3EFJ5EaQLyV0Tl5IFyahPPSNJ1F9ExrckdP7ZasfaxPalpDH7/ntl8nBi4wV38Plw2TmeDu2SaRGAnqSbVOybYRti+lHf+N7SO1oZKKK4QMadan12DJT6SLkcnTYDQRzbIwQVMcCdXsSavtwOCHO8bATU+U2jzpCMNZdVWA6t4XEE8uwdijOrtKUBi7MPoothPVTQsLigiU9iOHOcI4rw6m5KQM+LoMogiywCT2DpEsCICsL3g6G+zZPL7H/jfClCTSbu/imWxCWeMy04+auEhpuNGZ4F1CrJieBcoX7iMjfd1yetgvEgUd4LJjq4E2Bad/c4OxD+IGegV2JzmY7z4oQdP5Nmc4=
