language: php

php:
  - 7.1

before_script:
  - cp .env.testing .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - chmod 777 public/storage/recommend

script:
  - php artisan key:generate
  - vendor/bin/phpunit

notifications:
  email: false
